CSCwd08548 : pxGrid Cloud SDK documentation missing reconnect handling
cisco-pxgrid/cloud-sdk-go pull request #12
Opened 2022-11-22 11:11 UTC by kamalrajmadhurakasan

Issue: pxGrid Cloud SDK documentation missing reconnect handling

Solution: Introduced a reconnect logic in SDK itself.

2022-11-22 17:28 UTC, alei121 requested changes

2022-11-22 17:28 UTC, alei121 commented on app.go
> +		var reconnectDelay int64 = 1
Let's use a bigger delay. 1s is too small. And there should be a max.
Let's use delay of 30s and increase 30s for each consecutive failures until max of 2m.
We can use time.Duration directly here.
Something like this: https://go.dev/play/p/LW6tgcfUTd1
Adjust the backoffFactory only. The reconnectDelay and reconnectBackoff should be constant

2022-11-22 17:28 UTC, alei121 commented on app.go
> +				reconnectDelay += 1
Increase backoffFactor to max of 3. That should give us max of 2m

2022-11-22 17:28 UTC, alei121 commented on app.go
> +				reconnectDelay = 1
Reset backoffFactory to 0

2022-11-24 16:14 UTC, alei121 submitted a review, later dismissed

2022-11-29 05:58 UTC, balajithulasinathan approved these changes

2022-11-30 21:45 UTC, alei121 requested changes

2022-11-30 21:45 UTC, alei121 commented on app.go
> -			zeroByteArray(credentials.ApiKey)
Don't change the functionality.
I think it is the test code issue. 
https://github.com/cisco-pxgrid/cloud-sdk-go/blob/main/app_test.go#L69

The credential is created outside of the GetCredential func so it is being reused.
Put the credential inside the GetCredential func and give it a try.

2022-11-30 21:45 UTC, alei121 commented on app.go
> -	// ApiKey will be zeroed after use, therefore AppConfig.GetCredentials function should provide new structure every invocation
Let's try to leave this as-is. See below comment.

2022-12-01 18:55 UTC, alei121 approved these changes

2022-12-01 19:17 UTC, merged